export const themes = {
    1: "Action",
    17: "Fantasy",
    18: "Science fiction",
    19: "Horror",
    20: "Thriller",
    21: "Survival",
    22: "Historical",
    23: "Stealth",
    27: "Comedy",
    28: "Business",
    31: "Drama",
    32: "Non-fiction",
    33: "Sandbox",
    34: "Educational",
    35: "Kids",
    38: "Open-World",
    39: "Warfare",
    40: "Party",
    41: "4X",
    43: "Mystery",
}